            - name: Generate-README.md-snake
  # You may pin to the exact commit or the version.
  uses: vertsan/blob/main/README.md@86feadc98414dbe18a55673ecfe45d013a10392c
  with:
    # <USERNAME>
    github_user_name: vertsan
    # <PATH OF THE GENERATED SVG FILE>
    svg_out_path: 
          
